CC=gcc
CFLAGS=-g
LDFLAGS=-lobc

all:
	mkdir -p build
	$(CC) $(CFLAGS) -c src/NSObject/NSObject.m $(LDFLAGS) -o build/NSObject.o
	$(CC) $(CFLAGS) -c src/NSString/NSString.m $(LDFLAGS) -o build/NSString.o
